# docker-compose.yml
version: '3'
services:
#  web:
#    build: .
#    ports:
#      - "8280:8080"
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
#      - SPRING_DATASOURCE_USERNAME=compose-postgres
#      - SPRING_DATASOURCE_PASSWORD=compose-postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB= bitnami-keycloak
  keycloak:
    image: bitnami/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_DATABASE_HOST=db
      - KEYCLOAK_DATABASE_USER=compose-postgres
      - KEYCLOAK_DATABASE_PASSWORD=compose-postgres
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8180:8080"
